trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/WebApplicationCICD/Dockerfile'
#        tags: |
#          $(tag)
    - task: VSBuild@1
      inputs:
        solution: '**\*.sln'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
        platform: 'any cpu'
        configuration: 'release'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  condition: succeeded()
  dependsOn: Build
  jobs:
  - deployment: deploy
    environment:
      name: env-QA
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              downloadPath: '$(System.ArtifactsDirectory)'
              artifactName: 'drop'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'SC-LEAR'
              appType: 'webApp'
              WebAppName: 'AppServiceLEAR'
              packageForLinux: '$(System.DefaultWorkingDirectory)/drop/*.zip'