# Docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/WebApplicationCICD/Dockerfile'
        tags: |
          $(tag)
- stage: 
  dependsOn:
  - start
  condition: succeeded()
  jobs:
  - deployment: deploy
    environment:
      name: env-QA
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'SC-LEAR'
              appType: 'webApp'
              WebAppName: 'AppServiceLEAR'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'